---
global:
  spec:
    namespace: argocd
    source:
      repoURL: https://github.com/muhlba91/muehlbachler-public-services-cluster-applications.git
      targetRevision: HEAD
    values:
      repoURL: https://github.com/muhlba91/muehlbachler-public-services-cluster-applications.git
      targetRevision: HEAD
    syncWave: 0
    helm:
      enabled: false
      valueFiles:
        - values.yaml
    enableAutomated: false
    syncOptions: []

applications:
  argocd:
    project: "infrastructure-{{ $.Values.global.projectEnvironment }}"
    path: infrastructure/charts/argocd
    disabled: false
    namespace: argocd
    releaseName: argocd-{{ $.Values.global.environment }}
    helm: true
    syncWave: -2000
    ignoreDifferences:
      - group: "*"
        kind: "*"
        managedFieldsManagers:
          - externalsecrets.external-secrets.io/argocd-notifications-secret
  external-secrets:
    project: "infrastructure-{{ $.Values.global.projectEnvironment }}"
    path: infrastructure/charts/external-secrets
    releaseName: external-secrets
    disabled: false
    namespace: external-secrets
    helm: true
    syncWave: -750
  external-secrets-stores:
    project: "infrastructure-{{ $.Values.global.projectEnvironment }}"
    path: infrastructure/kustomizations/external-secrets-stores
    releaseName: external-secrets-stores
    disabled: false
    namespace: external-secrets
    helm: false
    syncWave: -500
