---
labels: &labels
  - tuxnet
  - vpn
  - dev

runnerConfig:
  replicas: 0
  minReplicas: 0
  maxReplicas: 3
  scaling:
    scaleUpThreshold: '0.9'
    scaleDownThreshold: '0.30'
    scaleUpAdjustment: 1
    scaleDownAdjustment: 1
runners:
  repositories: []
  organizations: []

actions-runner-controller:
  defaultScaleDownDelay: 5m

  authSecret:
    enabled: true
    create: false
    name: actions-runner-controller-auth

  runner:
    statusUpdateHook:
      enabled: true
