---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-email-muehlbachler-io
spec:
  acme:
    email: "noreply@muehlbachler.xyz"
    privateKeySecretRef:
      name: cluster-issuer-email-muehlbachler-io-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - selector:
          dnsZones:
            - email.muehlbachler.io
        dns01:
          cloudDNS:
            project: muehlbachler-dns
