creation_rules:
  - unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    gcp_kms: projects/public-services-402810/locations/europe/keyRings/infrastructure-encryption/cryptoKeys/infrastructure-encryption
