---
domain: &domain argocd.public.muehlbachler.io
url: &url https://argocd.public.muehlbachler.io

argo-cd:
  fullnameOverride: argocd-prod

  server:
    service:
      type: ClusterIP

    ingress:
      enabled: true
      hosts:
        - *domain
      tls:
        - secretName: argocd-tls-cert
          hosts:
            - *domain

  notifications:
    argocdUrl: *url

    notifiers:
      service.email.homelab: |
        username: $email-username
        password: $email-password
        host: $email-host
        port: 587
        from: $email-from
        html: true
    subscriptions:
      - recipients:
          - slack:announcements-public-services-cluster
        triggers:
          - on-health-degraded
          - on-sync-failed
      - recipients:
          - slack:announcements-public-services-cluster
        triggers:
          - on-deployed
          - on-sync-status-unknown
