---
tuxnetProject: &tuxnet_project tuxnet-385112 # FIXME: cross-project

zones: # FIXME: domains
  home.muehlbachler.io:
    project: *tuxnet_project

acme:
  email: "noreply@muehlbachler.xyz"

cert-manager:
  installCRDs: true

  tolerations:
    - operator: Exists

  extraArgs:
    - "--dns01-recursive-nameservers-only"
    - "--dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53"

  webhook:
    resources:
      requests:
        cpu: 5m
        memory: 40Mi
      limits:
        cpu: 50m
        memory: 56Mi

  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 136Mi
      limits:
        cpu: 100m
        memory: 192Mi

  resources:
    requests:
      cpu: 5m
      memory: 96Mi
    limits:
      cpu: 50m
      memory: 128Mi
