---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: simplelogin-redis
spec:
  releaseName: simplelogin-redis
  targetNamespace: simplelogin
  chart:
    spec:
      chart: redis
      version: 19.1.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: simplelogin-redis-values
      valuesKey: values.yaml
