---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fh-burgenland-argocd-extensions
spec:
  targetNamespace: fh-burgenland-argocd
  sourceRef:
    kind: GitRepository
    name: cluster-applications
  path: ./fh-burgenland/argocd/extensions/
  wait: true
