---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fh-burgenland-bswe-groups
spec:
  targetNamespace: fh-burgenland-argocd
  sourceRef:
    kind: GitRepository
    name: cluster-applications
  path: ./fh-burgenland/argocd/groups/
  wait: false
