---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: simplelogin-extensions
spec:
  targetNamespace: simplelogin
  sourceRef:
    kind: GitRepository
    name: cluster-applications
  path: ./applications/simplelogin/extensions/
  wait: false
