---
global:
  fullnameOverride: librechat

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/danny-avila/librechat
          pullPolicy: IfNotPresent
          tag: v0.6.10

        envFrom:
          - configMapRef:
              name: librechat-env
          - secretRef:
              name: librechat-secrets
          - secretRef:
              name: librechat-meilisearch-master-key

        resources:
          requests:
            cpu: 100m
            memory: 288Mi
          limits:
            cpu: 500m
            memory: 384Mi

serviceAccount:
  create: true

defaultPodOptions:
  automountServiceAccountToken: false

service:
  main:
    ports:
      http:
        port: 3080

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cluster-issuer-muehlbachler-io
      external-dns.alpha.kubernetes.io/provider: public
    hosts:
      - host: &domain gpt.muehlbachler.io # FIXME: librechat - url
        paths:
          - path: /
            pathType: ImplementationSpecific
            service:
              name: librechat
              port: 3080
    tls:
      - secretName: simplelogin-tls-cert
        hosts:
          - *domain

persistence:
  config:
    enabled: true
    type: configMap
    name: librechat-config
    defaultMode: 511
    advancedMounts:
      main:
        main:
          - path: /app/librechat.yaml
            subPath: librechat.yaml
