apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: doppler-auth-email
data:
    token: ENC[AES256_GCM,data:ioH7oOmmoq6LqxIX3EcUQ8KpPatfwpam4aQqoP7/tvwBM993h9cwJidJn4ThubWuMbIulGeSw/NA1UX7Xds9cSH6OgIZuwOt,iv:L8neLJkdbINoCGRsoCeILPTsdC8HM786jRWpzApElD0=,tag:dvhox5x1jcy7ceEsknZ3vg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/public-services-402810/locations/europe/keyRings/infrastructure-encryption/cryptoKeys/infrastructure-encryption
          created_at: "2023-10-22T11:08:17Z"
          enc: CiQAvgA/t2wyW+Y/217BHNXA7etexUBvyHMWO6LSyWe85gdOy0ASSAB99kCJ04dszHYWu1numb8xg1Yv/tPLfwQoyFVmqG7BBEcnsXqOg0W6yCsGzGym1/QkgV87ygjINvpNaYT6cM7bpSeTu2IHPw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-22T11:08:17Z"
    mac: ENC[AES256_GCM,data:ePe1L4qZdnUwG60DxnVCE5wohW52xuQ7ZBZDsgB2M64afDo7gr+xiZe9UMb95noZ2xJy+9deUOPYwrSZdvxm9C9U7g4NAmxpQ+MSFl/EKv5rw5UffZZCe9EkdqV35DgENvtH3xaw07pMV+jyF2b3DhAYr6WpajgFFnD69Ry39ns=,iv:J776WzIdrYumu/ZbQdDrn1sjIgkjdHoAM7szNJrVY5U=,tag:VOglBRfztclg9w/49WZZYg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
