apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: doppler-auth-tailscale
data:
    token: ENC[AES256_GCM,data:Yf+tFaw3gSt6O2I2FuB5xVPm5ftmMAeQyBBpQggD5PHwGowrbesXqjLfnxazu3c0WoU2KOaQZ/Wv9YFIiVerRos9xycNhzEb,iv:N5kodCufQYRAYb69NqLnehpZePtxcTlplmrsTL9DcBY=,tag:ufk9IQVr5FCP846S49Crog==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/public-services-402810/locations/europe/keyRings/infrastructure-encryption/cryptoKeys/infrastructure-encryption
          created_at: "2023-10-22T11:08:18Z"
          enc: CiQAvgA/t7xvpNtnvAEe+/zefMV8hRbbAq4ydezYbuRqebIxJTYSSQB99kCJcj/JJImBony+a+Jw+uvLto1LUroXbuBFmFTM/tyehU0LZ7enFfcjUGWg5ZnX3HPTcBhvGpiOT122WFs/03tRX82p67c=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-22T11:08:18Z"
    mac: ENC[AES256_GCM,data:XR5UBxTBBgz/C4Gyk5axRqWpCFJuWrSeRgovhb7HDbgfpCSzEhvNNLADGP/DwSMqWGnpjRE538ZS4MCZZ9N7ncqpgHeuXl3avsgSbEduU8CdHfgUb8/EIjO0Sh7opBSop3I/QAGmNF/xtBgrL3jm1QGlym2zgfL/c8Qrtvx13Ww=,iv:YjyjaNZ67JYFos5+v8wiySF4Gsb+5hcHZ5xeuc//bfA=,tag:AkcWpe8q8+xdwkn0/puz1w==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
