apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: doppler-auth-database
data:
    token: ENC[AES256_GCM,data:tE4IYtJ654anVQi1iJ17QNNgEDrDMxw093iTgR7OGHC/K/3Bx3LK5e8H5IDiM5FnlcdJzsQuUctokIMe8Ec0g3L7oxPE+zyr,iv:wh8riyuxnb0n7vyhhB617u132k4p0DK7wn+ESnlkbJg=,tag:EHVu0mI27LW8HmoBKkatqw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/public-services-402810/locations/europe/keyRings/infrastructure-encryption/cryptoKeys/infrastructure-encryption
          created_at: "2023-10-22T11:08:17Z"
          enc: CiQAvgA/t4RjYCjT8uGyFny5WkSfsziwmXrw4yEpJw3XL/Ic2TISSQB99kCJ8+rSBh2lYWgr2EG0oJxp8FWkSv3XUaTBnpvJqEmh/wVCsHd37TwKfQZkpUsAmxk4G9tbwphBBdIiqdtLWj/QlscGh78=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-22T11:08:17Z"
    mac: ENC[AES256_GCM,data:q7DSzn5qvhdAo/G1oVx+lyykKi/kY3IrSIgFgdLFt4HGV+1Y1SW8oZXkdV3l2UICAGcfChWAd5NCCos6QpcFa3nEpJacs+EfC0HksS/uMsyM3BkqlSRaRHJBy07i93++tvsBSVL9FJLgGfe9PX6TRYqgPFMqGiUPzG8GUbZ1gpo=,iv:t9oSz1mI4ZtBLpQX+rpNSAqiKdJ3FLupy58Ihhksh14=,tag:zd9i3FAcZ5vdkNzQfcZ2Sg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
