---
resources:
  requests:
    cpu: 3m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 56Mi

webhook:
  resources:
    requests:
      cpu: 2m
      memory: 30Mi
    limits:
      cpu: 50m
      memory: 48Mi

certController:
  resources:
    requests:
      cpu: 3m
      memory: 56Mi
    limits:
      cpu: 50m
      memory: 96Mi
