---
external-dns:
  image:
    registry: registry.k8s.io
    repository: external-dns/external-dns
    tag: v0.13.6

  tolerations:
    - operator: Exists

  sources:
    - service
    - ingress

  interval: 5m

  logLevel: error

  domainFilters: # FIXME: domains
    - home.muehlbachler.io
  annotationFilter: external-dns.alpha.kubernetes.io/provider=public

  txtOwnerId: external-dns-public-cluster-dev-google # FIXME: naming
  provider: google
  google:
    serviceAccountSecret: external-dns-google
    project: tuxnet-385112 # FIXME: cross-project

  resources:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      cpu: 10m
      memory: 80Mi
