---
external-dns:
  image:
    registry: registry.k8s.io
    repository: external-dns/external-dns
    tag: v0.13.6

  serviceAccount:
    create: false
    name: external-dns

  sources:
    - service
    - ingress

  interval: 5m

  logLevel: error

  domainFilters:
    - muehlbachler.io
  annotationFilter: external-dns.alpha.kubernetes.io/provider=public

  txtOwnerId: external-dns-public-services-cluster-dev-google
  provider: google
  google:
    project: muehlbachler-dns

  resources:
    requests:
      cpu: 5m
      memory: 45Mi
    limits:
      cpu: 10m
      memory: 64Mi
