---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: d1n-email-muehlbachler-io
  annotations:
    external-dns.alpha.kubernetes.io/provider: public
    simplelogin/owner: daniel
spec:
  endpoints: []