---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: k3e-email-muehlbachler-io
  annotations:
    external-dns.alpha.kubernetes.io/provider: public
    simplelogin/owner: katarzyna
spec:
  endpoints: []
