---
fullnameOverride: traefik

providers:
  kubernetesCRD:
    allowExternalNameServices: true
    allowEmptyServices: true
  kubernetesIngress:
    allowExternalNameServices: true
    allowEmptyServices: true
    publishedService:
      enabled: true

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"

ports:
  traefik:
    expose:
      default: true
  web:
    redirectTo:
      port: websecure
    forwardedHeaders:
      trustedIPs:
        - 10.0.0.0/8
      insecure: true
    proxyProtocol:
      trustedIPs:
        - 10.0.0.0/8
      insecure: true
  websecure:
    forwardedHeaders:
      trustedIPs:
        - 10.0.0.0/8
      insecure: true
    proxyProtocol:
      trustedIPs:
        - 10.0.0.0/8
      insecure: true

service:
  ipFamilyPolicy: PreferDualStack
  externalTrafficPolicy: Local
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.100.72.1,2a01:4f8:121:14e2:100:3:3:1"

resources:
  requests:
    cpu: 10m
    memory: 56Mi
  limits:
    cpu: 100m
    memory: 128Mi
