---
installCRDs: true

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: pub-svcs-cert-manager-prod@public-services-402810.iam.gserviceaccount.com

extraArgs:
  - "--dns01-recursive-nameservers-only"
  - "--dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53"

webhook:
  resources:
    requests:
      cpu: 2m
      memory: 16Mi
    limits:
      cpu: 50m
      memory: 32Mi

cainjector:
  resources:
    requests:
      cpu: 2m
      memory: 40Mi
    limits:
      cpu: 50m
      memory: 56Mi

resources:
  requests:
    cpu: 2m
    memory: 28Mi
  limits:
    cpu: 100m
    memory: 56Mi
