---
# TODO: TS_AUTH_KEY
# this key expires *in* 90 days! => add key rotation

serviceAccountName: &service_account_name tailscale

app-template:
  controllers:
    main:
      type: daemonset
      containers:
        main:
          image:
            repository: ghcr.io/tailscale/tailscale
            tag: v1.50.1
            pullPolicy: IfNotPresent

          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-secrets
                  key: auth-key
            - name: TS_USERSPACE
              value: "false"
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TS_EXTRA_ARGS
              value: "--accept-routes"

          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW

          resources:
            requests:
              cpu: 3m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi

  defaultPodOptions:
    hostNetwork: true

  serviceAccount:
    create: true
    name: *service_account_name

  service:
    main:
      enabled: false
