---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-extensions
spec:
  targetNamespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: cluster-applications
  path: ./infrastructure/external-secrets/extensions/
  interval: 5m # FIXME:
  retryInterval: 2m
  timeout: 3m
  wait: true
  prune: true
  force: false
