---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simplelogin-init
data:
  init.sh: |
    #!/bin/bash

    # needed for importing gpg keys
    echo "[init] creating gpg directory..."
    mkdir /sl/gnupg

    # application initialization
    echo "[init] initializing application..."
    alembic upgrade head
    python init_app.py

    # set all users as premium users
    echo "[init] set users as premium..."
    apt-get update
    apt-get install --yes postgresql-client
    psql -c "UPDATE users SET lifetime = TRUE;"
