---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simplelogin-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-simplelogin
  target:
    name: simplelogin-oidc
  data:
    - secretKey: OIDC_AUTHORIZATION_URL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OIDC_AUTHORIZATION_URL
    - secretKey: OIDC_USER_INFO_URL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OIDC_USER_INFO_URL
    - secretKey: OIDC_TOKEN_URL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OIDC_TOKEN_URL
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OIDC_CLIENT_SECRET
