---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simplelogin-database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-database
  target:
    name: simplelogin-database
    template:
      engineVersion: v2
      data:
        DB_URI: "postgresql://{{ .db_user }}:{{ .db_password }}@{{ .db_host }}:{{ .db_port }}/{{ .db_name }}"
  data:
    - secretKey: db_host
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_CLUSTER_POSTGRESQL_HOST
    - secretKey: db_port
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_CLUSTER_POSTGRESQL_PORT
    - secretKey: db_name
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_CLUSTER_POSTGRESQL_DATABASE_SIMPLELOGIN
    - secretKey: db_user
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_CLUSTER_POSTGRESQL_USER_SIMPLELOGIN
    - secretKey: db_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_CLUSTER_POSTGRESQL_PASSWORD_SIMPLELOGIN
