---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simplelogin-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-mail-relay
  target:
    name: simplelogin-config
    template:
      engineVersion: v2
      data:
        environment: |
          # Disable onboarding emails
          # For self-hosted instance
          DISABLE_ONBOARDING=false

          # Close registration. Avoid people accidentally creating new account on a self-hosted SimpleLogin
          DISABLE_REGISTRATION=1 # TODO: set this to enable/disable registration

          # Only print email content, not sending it, for local development
          # NOT_SEND_EMAIL=0

          # Server url
          URL=https://admin.email.muehlbachler.io

          # apply colored log to facilitate local development
          # COLOR_LOG=true

          # domain used to create alias
          EMAIL_DOMAIN=relay.email.muehlbachler.io

          # Allow SimpleLogin to enforce SPF by using the extra headers from postfix
          ENFORCE_SPF=true

          # other domains that can be used to create aliases, in addition to EMAIL_DOMAIN
          # OTHER_ALIAS_DOMAINS=["domain1.com", "domain2.com"]

          # domains that can be used to create aliases. If set, override OTHER_ALIAS_DOMAINS
          # ALIAS_DOMAINS=[]

          # (optional) domains that are only available to premium accounts
          # PREMIUM_ALIAS_DOMAINS=["premium.com"]

          # the alias domain used when creating the first alias for user, default to EMAIL_DOMAIN if not set
          # FIRST_ALIAS_DOMAIN = another-domain.com

          # transactional email is sent from this email address
          SUPPORT_EMAIL="noreply@email.muehlbachler.io"
          SUPPORT_NAME="E-Mail Relay"

          # To use VERP
          # prefix must end with + and suffix must start with +
          # BOUNCE_PREFIX = "bounces+"
          # BOUNCE_SUFFIX = "+@sl.local"
          # same as BOUNCE_PREFIX but used for reply phase. Note it doesn't have the plus sign (+) at the end.
          # BOUNCE_PREFIX_FOR_REPLY_PHASE = "bounce_reply"

          # to receive general stats.
          # ADMIN_EMAIL=admin@sl.local

          # Max number emails user can generate for free plan
          # Set to 5 by default
          # MAX_NB_EMAIL_FREE_PLAN=5

          # custom domain needs to point to these MX servers
          EMAIL_SERVERS_WITH_PRIORITY=[(10, "relay.email.muehlbachler.io."), (20, "relay.email.muehlbachler.io.")]

          # By default, new aliases must end with ".{random_word}". This is to avoid a person taking all "nice" aliases.
          # this option doesn't make sense in self-hosted. Set this variable to disable this option.
          DISABLE_ALIAS_SUFFIX=1

          # If you want to use another MTA to send email, you could set the address of your MTA here
          # By default, emails are sent using the the same Postfix server that receives emails
          POSTFIX_SERVER={{ .postfix_server }}

          # By default use postfix port 25. This param is used to override the Postfix port,
          # useful when using another SMTP server when developing locally
          POSTFIX_PORT=1025

          # POSTFIX_TIMEOUT=10

          # the DKIM private key used to compute DKIM-Signature
          DKIM_PRIVATE_KEY_PATH=/dkim.key

          # DB Connection
          DB_URI=postgresql://{{ .db_user }}:{{ .db_password }}@{{ .db_host }}:{{ .db_port }}/{{ .db_name }}

          FLASK_SECRET={{ .flask_secret }}

          # AWS params
          BUCKET={{ .aws_bucket }}
          AWS_ACCESS_KEY_ID={{ .aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY={{ .aws_secret_key }}
          AWS_REGION={{ .aws_region }}

          # OpenId key
          # OPENID_PRIVATE_KEY_PATH=local_data/jwtRS256.key
          # OPENID_PUBLIC_KEY_PATH=local_data/jwtRS256.key.pub

          # Words to generate random email alias
          # WORDS_FILE_PATH=local_data/test_words.txt

          # Where to store GPG Keyring
          GNUPGHOME=/sl/gnupg

          # By default, files are uploaded to s3
          # Set this variable to use the local "static/upload/" directory instead
          #LOCAL_FILE_UPLOAD=1

          # set the 2 below variables to enable hCaptcha
          # HCAPTCHA_SECRET=very_long_string
          # HCAPTCHA_SITEKEY=00000000-0000-0000-0000-000000000000

          # Spamassassin server
          # SPAMASSASSIN_HOST = 127.0.0.1

          # if set, used to sign the forwarding emails
          # PGP_SENDER_PRIVATE_KEY_PATH=local_data/private-pgp.asc

          # set the frequency limit on alias creation
          # ALIAS_LIMIT = "100/day;50/hour;5/minute"

          # whether to enable spam scan using SpamAssassin
          # ENABLE_SPAM_ASSASSIN = 1

          # Have I Been Pwned
          # HIBP_SCAN_INTERVAL_DAYS = 7
          # HIBP_API_KEYS=[]

          # POSTMASTER = postmaster@example.com

          # TEMP_DIR = /tmp

          # ALIAS_AUTOMATIC_DISABLE=true

          # domains that can be present in the &next= section when using absolute urls
          ALLOWED_REDIRECT_DOMAINS=[]

          # DNS nameservers to be used by the app
          # Multiple nameservers can be specified, separated by ','
          NAMESERVERS="1.1.1.1"
  data:
    - secretKey: aws_bucket
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_AWS_BUCKET
    - secretKey: aws_region
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_AWS_REGION
    - secretKey: aws_access_key_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_AWS_ACCESS_KEY_ID
    - secretKey: aws_secret_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_AWS_SECRET_ACCESS_KEY
    - secretKey: flask_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_FLASK_SECRET
    - secretKey: postfix_server
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_POSTFIX_SERVER
    - secretKey: db_host
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_CLUSTER_POSTGRESQL_HOST
      sourceRef:
        storeRef:
          name: doppler-auth-database
          kind: ClusterSecretStore
    - secretKey: db_port
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_CLUSTER_POSTGRESQL_PORT
      sourceRef:
        storeRef:
          name: doppler-auth-database
          kind: ClusterSecretStore
    - secretKey: db_name
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_CLUSTER_POSTGRESQL_DATABASE_SIMPLELOGIN
      sourceRef:
        storeRef:
          name: doppler-auth-database
          kind: ClusterSecretStore
    - secretKey: db_user
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_CLUSTER_POSTGRESQL_USER_SIMPLELOGIN
      sourceRef:
        storeRef:
          name: doppler-auth-database
          kind: ClusterSecretStore
    - secretKey: db_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_CLUSTER_POSTGRESQL_PASSWORD_SIMPLELOGIN
      sourceRef:
        storeRef:
          name: doppler-auth-database
          kind: ClusterSecretStore
