---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dkim-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-mail-relay
  target:
    name: dkim-key
  data:
    - secretKey: private_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_DKIM_PRIVATE_KEY
    - secretKey: public_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_DKIM_PUBLIC_KEY
