---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dkim-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: dkim-key
  data:
    - secretKey: private_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mail-relay-dkim
        property: private_key
    - secretKey: public_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mail-relay-dkim
        property: public_key
