---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simplelogin-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-mail-relay
  target:
    name: simplelogin-config
  data:
    - secretKey: BUCKET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_AWS_BUCKET
    - secretKey: AWS_REGION
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_AWS_REGION
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_AWS_SECRET_ACCESS_KEY
    - secretKey: FLASK_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_FLASK_SECRET
    - secretKey: POSTFIX_SERVER
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MAIL_RELAY_POSTFIX_SERVER
