---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simplelogin
resources:
  - ./external-secret-dkim-key.yaml
  - ./external-secret-simplelogin-database.yaml
  - ./external-secret-simplelogin-config.yaml
  - ./configmap-init.yaml
  - ./configmap.yaml
