---
global:
  spec:
    namespace: argocd
    source:
      repoURL: https://github.com/muhlba91/muehlbachler-public-services-cluster-applications.git
      targetRevision: argocd
    values:
      repoURL: https://github.com/muhlba91/muehlbachler-public-services-cluster-applications.git
      targetRevision: argocd
    syncWave: 0
    helm:
      enabled: false
      valueFiles:
        - values.yaml
    enableAutomated: false
    syncOptions: []

applications:
  authentik:
    project: "applications-{{ $.Values.global.projectEnvironment }}"
    path: applications/charts/authentik
    releaseName: authentik
    disabled: false
    namespace: authentik
    helm: true
    syncWave: -500
  github-actions-runner-controller:
    project: "applications-{{ $.Values.global.projectEnvironment }}"
    path: applications/charts/github-actions-runner-controller
    releaseName: github-actions-runner-controller
    disabled: false
    namespace: github-actions-runner-controller
    helm: true
    syncOptions:
      - ServerSideApply=true
    ignoreDifferences:
      - group: actions.summerwind.dev
        kind: RunnerDeployment
        jsonPointers:
          - /spec/replicas
