---
fullnameOverride: redis

architecture: standalone

auth:
  enabled: false

master:
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 15m
      memory: 16Mi
    limits:
      cpu: 50m
      memory: 32Mi

networkPolicy:
  enabled: false
