---
fullnameOverride: redis

architecture: standalone

auth:
  enabled: false

master:
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi

networkPolicy:
  enabled: false
