---
traefik:
  fullnameOverride: traefik

  providers:
    kubernetesCRD:
      allowExternalNameServices: true
      allowEmptyServices: true
    kubernetesIngress:
      allowExternalNameServices: true
      allowEmptyServices: true
      publishedService:
        enabled: false

  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    - "--providers.kubernetesingress.ingressendpoint.ip=10.200.200.1"

  ports:
    traefik:
      expose: false
    web:
      redirectTo: websecure
      proxyProtocol:
        insecure: true
        trustedIPs:
          - 10.0.0.0/8
    websecure:
      proxyProtocol:
        insecure: true
        trustedIPs:
          - 10.0.0.0/8
    ldaps:
      port: 8636
      expose: true
      exposedPort: 636
      protocol: TCP

  service:
    type: ClusterIP
    # ipFamilyPolicy: PreferDualStack
    externalIPs:
      - 10.200.200.1
    spec:
      clusterIP: None

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 192Mi
