---
global:
  security:
    allowInsecureImages: true

image:
  registry: registry.k8s.io
  repository: external-dns/external-dns
  tag: v0.16.1

crd:
  create: true

sources:
  - crd
  - service
  - ingress
  - traefik-proxy
  - gateway-grpcroute
  - gateway-httproute
  - gateway-tlsroute
  - gateway-udproute
  - gateway-tcproute

interval: 2m

logLevel: warning

domainFilters:
  - muehlbachler.io
  - muehlbachler.xyz
annotationFilter: external-dns.alpha.kubernetes.io/provider=public
managedRecordTypesFilters:
  - A
  - AAAA
  - CNAME
  - MX
  - TXT

registry: noop
txtOwnerId: external-dns-public-services-cluster-prod
txtPrefix: extdns-
provider: google
google:
  serviceAccountSecret: external-dns-google
  project: muehlbachler-dns
extraArgs:
  traefik-disable-legacy: ""

resources:
  requests:
    cpu: 2m
    memory: 48Mi
  limits:
    cpu: 10m
    memory: 80Mi
