---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: librechat-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-librechat
  target:
    name: librechat-secrets
  data:
    - secretKey: MONGO_URI
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: PUBLIC_SERVICES_MONGODB_LIBRECHAT_URI
    - secretKey: OPENAI_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OPENAI_API_KEY
    - secretKey: DALLE_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: DALLE_API_KEY
    - secretKey: ASSISTANTS_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ASSISTANTS_API_KEY
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ANTHROPIC_API_KEY
    # - secretKey: GOOGLE_API_KEY # FIXME: librechat - google search
    #   remoteRef:
    #     conversionStrategy: Default
    #     decodingStrategy: None
    #     key: GOOGLE_API_KEY
    # - secretKey: GOOGLE_CSE_ID
    #   remoteRef:
    #     conversionStrategy: Default
    #     decodingStrategy: None
    #     key: GOOGLE_CSE_ID
    - secretKey: CREDS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: CREDS_KEY
    - secretKey: CREDS_IV
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: CREDS_IV
    - secretKey: JWT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: JWT_SECRET
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: JWT_REFRESH_SECRET
    - secretKey: OPENID_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OPENID_CLIENT_ID
    - secretKey: OPENID_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OPENID_CLIENT_SECRET
    - secretKey: OPENID_ISSUER
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OPENID_WELL_KNOWN_CONFIGURATION
    - secretKey: OPENID_SESSION_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: JWT_SECRET
    - secretKey: EMAIL_HOST
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: EMAIL_HOST
    - secretKey: EMAIL_PORT
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: EMAIL_PORT
    - secretKey: EMAIL_ENCRYPTION
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: EMAIL_ENCRYPTION
    - secretKey: EMAIL_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: EMAIL_USERNAME
    - secretKey: EMAIL_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: EMAIL_PASSWORD
    - secretKey: FIREBASE_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: FIREBASE_API_KEY
    - secretKey: FIREBASE_AUTH_DOMAIN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: FIREBASE_AUTH_DOMAIN
    - secretKey: FIREBASE_PROJECT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: FIREBASE_PROJECT_ID
    - secretKey: FIREBASE_STORAGE_BUCKET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: FIREBASE_STORAGE_BUCKET
    - secretKey: FIREBASE_MESSAGING_SENDER_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: FIREBASE_MESSAGING_SENDER_ID
    - secretKey: FIREBASE_APP_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: FIREBASE_APP_ID
