---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: argocd-oidc
  data:
    - secretKey: clientID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: fh-burgenland-argocd-oidc
        property: client_id
    - secretKey: clientSecret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: fh-burgenland-argocd-oidc
        property: client_secret
