---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: argocd-github
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: appId
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: fh-burgenland-oidc
        property: app_id
    - secretKey: installationId
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: fh-burgenland-oidc
        property: installation_id
    - secretKey: privateKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: fh-burgenland-oidc
        property: private_key
