---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: ghcr-credentials
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: fh-burgenland-github
        property: dockerconfigjson
