---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fh-burgenland-argocd
resources:
  - ./external-secret-argocd-oidc.yaml
  - ./repository-apps.yaml
  - ./external-secret-assignment-repository.yaml
  - ./application-app-of-apps.yaml
