---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: &name doppler-auth-database
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            namespace: external-secrets
            name: *name
            key: token
