---
apiVersion: v2
name: external-dns
description: Customized External DNS for Google

version: 1.0.0

type: application

maintainers:
  - name: Daniel Muehlbachler-Pietrzykowski
    email: daniel@muehlbachler.io

appVersion: "0.0.0"

dependencies:
  - name: external-dns
    version: 6.27.0
    repository: https://charts.bitnami.com/bitnami
