---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
spec:
  releaseName: reflector
  targetNamespace: reflector
  chart:
    spec:
      chart: reflector
      version: 9.1.6
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: reflector-values
      valuesKey: values.yaml
