{{- range .Values.runners.organizations }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .organization | replace "/" "--" }}
spec:
  replicas: {{ default $.Values.runnerConfig.replicas .replicas }}
  template:
    spec:
      ephemeral: true
    {{- with .nodeSelector }}
      nodeSelector: {{ . | toYaml |  nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations: {{ . | toYaml |  nindent 8 }}
    {{- end }}
      containers:
        - name: docker
          resources: {}
          env:
            - name: RUNNER_TOOL_CACHE
              value: /runner/_work/hostedtoolcache
        - name: runner
          resources: {}
          env:
            - name: RUNNER_TOOL_CACHE
              value: /runner/_work/hostedtoolcache
      organization: {{ .organization }}
    {{- with .resources }}
      resources: {{ . | toYaml |  nindent 8 }}
    {{- end }}
    {{- with .labels }}
      labels: {{ . | toYaml |  nindent 8 }}
    {{- end }}
{{- end }}
