---
generators:
  - ./secret-generator.yml

resources:
  - ./stores/argocd.yml
  - ./stores/authentik.yml
  - ./stores/database.yml
  - ./stores/email.yml
  - ./stores/github.yml
  - ./stores/tailscale.yml
