---
global:
  fullnameOverride: meilisearch

environment:
  MEILI_ENV: production
auth:
  existingMasterKeySecret: librechat-meilisearch-master-key

persistence:
  enabled: false
  storageClass: ""
  size: 1Gi  

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
