apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: doppler-auth-email
data:
    token: ENC[AES256_GCM,data:3zdG39JpZ6jq4EKCUk52i9ruAo9Cvvd3/MG5qoJ9I9hqujIcyuG0+AZ5MDzqb75Hxrn23EAJIpry88AgEEbsa7Diw1veskwN,iv:Fuq+PyDQnidcjGes14uqyEXpx0mW6rYV1ASlBeQY2w4=,tag:VVsVEAGS2lqzX9R6K8xVHg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/public-services-402810/locations/europe/keyRings/infrastructure-encryption/cryptoKeys/infrastructure-encryption
          created_at: "2023-10-26T07:42:20Z"
          enc: CiQAvgA/twCMQNXrkweDQcwsJugEBlX5UOV9Q/c1sV1/nl9+wXQSSQB99kCJIGnov2HBHXwNRVw2+pjlwviqE6JNhy+4Jk0A7HSdlHotmeIjwASc3isGnIU8e20C5rrlNrU+axUKWeNNnLsQRzCMEp0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-26T07:42:21Z"
    mac: ENC[AES256_GCM,data:xnAk/naJSyVRmkFHw/mztNiAVXnX9vOphi4cGTTal4P2yV1iO9Rn8x05DB3BtqtOmqfQ2gyLGLAGFEuITsB7Hf7cI/p62VG7psLb2p1jA3qPsO8Oypy40At69eBba7Sx8FBftX4KaE34tPJzqaIZ/w7rtN+Km6AK0R8P4jJHSFU=,iv:wvnkjezn6OCTR3FOqw5kN+lwHIsWGSezCXtENNyq4IA=,tag:sxGugdbaISEpOAalY73p5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
