---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simplelogin-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: simplelogin-config
  data:
    - secretKey: BUCKET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: simplelogin-aws
        property: bucket
    - secretKey: AWS_REGION
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: simplelogin-aws
        property: region
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: simplelogin-aws
        property: access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: simplelogin-aws
        property: secret_access_key
    - secretKey: FLASK_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: simplelogin-flask-secret
        property: secret
    - secretKey: POSTFIX_SERVER
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mail-relay-postfix-server
        property: ipv4
