---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simplelogin-database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: simplelogin-database
    template:
      engineVersion: v2
      data:
        DB_URI: "postgresql://{{ .db_user }}:{{ .db_password }}@{{ .db_host }}:{{ .db_port }}/{{ .db_name }}"
        PGHOST: "{{ .db_host }}"
        PGPORT: "{{ .db_port }}"
        PGDATABASE: "{{ .db_name }}"
        PGUSER: "{{ .db_user }}"
        PGPASSWORD: "{{ .db_password }}"
  data:
    - secretKey: db_host
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgresql-connection
        property: host
    - secretKey: db_port
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgresql-connection
        property: port
    - secretKey: db_name
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgresql-database-simplelogin
        property: name
    - secretKey: db_user
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgresql-user-simplelogin
        property: user
    - secretKey: db_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgresql-user-simplelogin
        property: password
