---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simplelogin-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-auth
  target:
    name: simplelogin-oidc
  data:
    - secretKey: OIDC_AUTHORIZATION_URL # TODO: delete
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: zitadel
        property: authz_url
    - secretKey: OIDC_USER_INFO_URL # TODO: delete
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: zitadel
        property: user_info_url
    - secretKey: OIDC_TOKEN_URL # TODO: delete
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: zitadel
        property: token_url
    - secretKey: OIDC_WELL_KNOWN_URL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: zitadel
        property: well_known_url
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: simplelogin-oidc
        property: client_id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: simplelogin-oidc
        property: client_secret
