---
external-secrets:
  resources:
    requests:
      cpu: 5m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 70Mi

  webhook:
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 56Mi

  certController:
    resources:
      requests:
        cpu: 5m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 96Mi
