---
external-secrets:
  resources:
    requests:
      cpu: 5m
      memory: 55Mi
    limits:
      cpu: 50m
      memory: 72Mi

  webhook:
    resources:
      requests:
        cpu: 5m
        memory: 40Mi
      limits:
        cpu: 50m
        memory: 56Mi

  certController:
    resources:
      requests:
        cpu: 5m
        memory: 75Mi
      limits:
        cpu: 50m
        memory: 96Mi
