---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: d1n-email-muehlbachler-io
  annotations:
    external-dns.alpha.kubernetes.io/provider: public
spec:
  endpoints:
    - dnsName: _adsp._domainkey.d1n.email.muehlbachler.io
      recordTTL: 300
      recordType: TXT
      targets:
        - "\"dkim=all\""
    - dnsName: _dmarc.d1n.email.muehlbachler.io
      recordTTL: 300
      recordType: TXT
      targets:
        - "\"v=DMARC1; p=quarantine; pct=100; adkim=s; aspf=s\""
    - dnsName: d1n.email.muehlbachler.io
      recordTTL: 300
      recordType: TXT
      targets:
        - "\"v=spf1 include:email.muehlbachler.io -all\""
        # - sl-verification=vrflpflpdzcmgmhwprsnlleefceiwk
    - dnsName: dkim._domainkey.d1n.email.muehlbachler.io
      recordTTL: 300
      recordType: CNAME
      targets:
        - dkim._domainkey.email.muehlbachler.io
    - dnsName: dkim02._domainkey.d1n.email.muehlbachler.io
      recordTTL: 300
      recordType: CNAME
      targets:
        - dkim02._domainkey.email.muehlbachler.io
    - dnsName: dkim03._domainkey.d1n.email.muehlbachler.io
      recordTTL: 300
      recordType: CNAME
      targets:
        - dkim03._domainkey.email.muehlbachler.io
    - dnsName: d1n.email.muehlbachler.io
      recordTTL: 300
      recordType: MX
      targets:
        - 10 relay.email.muehlbachler.io
        - 20 relay.email.muehlbachler.io
